// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol_note.proto

package com.lys.protobuf;

public final class ProtocolNote {
  private ProtocolNote() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NotePageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NotePage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string pageDir = 1;</code>
     */
    boolean hasPageDir();
    /**
     * <code>optional string pageDir = 1;</code>
     */
    java.lang.String getPageDir();
    /**
     * <code>optional string pageDir = 1;</code>
     */
    com.google.protobuf.ByteString
        getPageDirBytes();

    /**
     * <code>optional string title = 2;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional int32 subject = 3;</code>
     */
    boolean hasSubject();
    /**
     * <code>optional int32 subject = 3;</code>
     */
    int getSubject();
  }
  /**
   * Protobuf type {@code NotePage}
   */
  public static final class NotePage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NotePage)
      NotePageOrBuilder {
    // Use NotePage.newBuilder() to construct.
    private NotePage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NotePage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NotePage defaultInstance;
    public static NotePage getDefaultInstance() {
      return defaultInstance;
    }

    public NotePage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NotePage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              pageDir_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              title_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              subject_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lys.protobuf.ProtocolNote.internal_static_NotePage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lys.protobuf.ProtocolNote.internal_static_NotePage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lys.protobuf.ProtocolNote.NotePage.class, com.lys.protobuf.ProtocolNote.NotePage.Builder.class);
    }

    public static com.google.protobuf.Parser<NotePage> PARSER =
        new com.google.protobuf.AbstractParser<NotePage>() {
      public NotePage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NotePage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NotePage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PAGEDIR_FIELD_NUMBER = 1;
    private java.lang.Object pageDir_;
    /**
     * <code>optional string pageDir = 1;</code>
     */
    public boolean hasPageDir() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string pageDir = 1;</code>
     */
    public java.lang.String getPageDir() {
      java.lang.Object ref = pageDir_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          pageDir_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string pageDir = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPageDirBytes() {
      java.lang.Object ref = pageDir_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pageDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private java.lang.Object title_;
    /**
     * <code>optional string title = 2;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBJECT_FIELD_NUMBER = 3;
    private int subject_;
    /**
     * <code>optional int32 subject = 3;</code>
     */
    public boolean hasSubject() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 subject = 3;</code>
     */
    public int getSubject() {
      return subject_;
    }

    private void initFields() {
      pageDir_ = "";
      title_ = "";
      subject_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPageDirBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, subject_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPageDirBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitleBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, subject_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lys.protobuf.ProtocolNote.NotePage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lys.protobuf.ProtocolNote.NotePage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NotePage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lys.protobuf.ProtocolNote.NotePage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NotePage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lys.protobuf.ProtocolNote.NotePage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NotePage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lys.protobuf.ProtocolNote.NotePage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NotePage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lys.protobuf.ProtocolNote.NotePage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lys.protobuf.ProtocolNote.NotePage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NotePage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NotePage)
        com.lys.protobuf.ProtocolNote.NotePageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lys.protobuf.ProtocolNote.internal_static_NotePage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lys.protobuf.ProtocolNote.internal_static_NotePage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lys.protobuf.ProtocolNote.NotePage.class, com.lys.protobuf.ProtocolNote.NotePage.Builder.class);
      }

      // Construct using com.lys.protobuf.ProtocolNote.NotePage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pageDir_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        subject_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lys.protobuf.ProtocolNote.internal_static_NotePage_descriptor;
      }

      public com.lys.protobuf.ProtocolNote.NotePage getDefaultInstanceForType() {
        return com.lys.protobuf.ProtocolNote.NotePage.getDefaultInstance();
      }

      public com.lys.protobuf.ProtocolNote.NotePage build() {
        com.lys.protobuf.ProtocolNote.NotePage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lys.protobuf.ProtocolNote.NotePage buildPartial() {
        com.lys.protobuf.ProtocolNote.NotePage result = new com.lys.protobuf.ProtocolNote.NotePage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pageDir_ = pageDir_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.subject_ = subject_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lys.protobuf.ProtocolNote.NotePage) {
          return mergeFrom((com.lys.protobuf.ProtocolNote.NotePage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lys.protobuf.ProtocolNote.NotePage other) {
        if (other == com.lys.protobuf.ProtocolNote.NotePage.getDefaultInstance()) return this;
        if (other.hasPageDir()) {
          bitField0_ |= 0x00000001;
          pageDir_ = other.pageDir_;
          onChanged();
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasSubject()) {
          setSubject(other.getSubject());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lys.protobuf.ProtocolNote.NotePage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lys.protobuf.ProtocolNote.NotePage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object pageDir_ = "";
      /**
       * <code>optional string pageDir = 1;</code>
       */
      public boolean hasPageDir() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string pageDir = 1;</code>
       */
      public java.lang.String getPageDir() {
        java.lang.Object ref = pageDir_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            pageDir_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string pageDir = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPageDirBytes() {
        java.lang.Object ref = pageDir_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pageDir_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string pageDir = 1;</code>
       */
      public Builder setPageDir(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pageDir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string pageDir = 1;</code>
       */
      public Builder clearPageDir() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pageDir_ = getDefaultInstance().getPageDir();
        onChanged();
        return this;
      }
      /**
       * <code>optional string pageDir = 1;</code>
       */
      public Builder setPageDirBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        pageDir_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      private int subject_ ;
      /**
       * <code>optional int32 subject = 3;</code>
       */
      public boolean hasSubject() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 subject = 3;</code>
       */
      public int getSubject() {
        return subject_;
      }
      /**
       * <code>optional int32 subject = 3;</code>
       */
      public Builder setSubject(int value) {
        bitField0_ |= 0x00000004;
        subject_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 subject = 3;</code>
       */
      public Builder clearSubject() {
        bitField0_ = (bitField0_ & ~0x00000004);
        subject_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NotePage)
    }

    static {
      defaultInstance = new NotePage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NotePage)
  }

  public interface NotePageSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NotePageSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .NotePage pages = 1;</code>
     */
    java.util.List<com.lys.protobuf.ProtocolNote.NotePage> 
        getPagesList();
    /**
     * <code>repeated .NotePage pages = 1;</code>
     */
    com.lys.protobuf.ProtocolNote.NotePage getPages(int index);
    /**
     * <code>repeated .NotePage pages = 1;</code>
     */
    int getPagesCount();
    /**
     * <code>repeated .NotePage pages = 1;</code>
     */
    java.util.List<? extends com.lys.protobuf.ProtocolNote.NotePageOrBuilder> 
        getPagesOrBuilderList();
    /**
     * <code>repeated .NotePage pages = 1;</code>
     */
    com.lys.protobuf.ProtocolNote.NotePageOrBuilder getPagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code NotePageSet}
   */
  public static final class NotePageSet extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NotePageSet)
      NotePageSetOrBuilder {
    // Use NotePageSet.newBuilder() to construct.
    private NotePageSet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NotePageSet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NotePageSet defaultInstance;
    public static NotePageSet getDefaultInstance() {
      return defaultInstance;
    }

    public NotePageSet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NotePageSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                pages_ = new java.util.ArrayList<com.lys.protobuf.ProtocolNote.NotePage>();
                mutable_bitField0_ |= 0x00000001;
              }
              pages_.add(input.readMessage(com.lys.protobuf.ProtocolNote.NotePage.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          pages_ = java.util.Collections.unmodifiableList(pages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lys.protobuf.ProtocolNote.internal_static_NotePageSet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lys.protobuf.ProtocolNote.internal_static_NotePageSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lys.protobuf.ProtocolNote.NotePageSet.class, com.lys.protobuf.ProtocolNote.NotePageSet.Builder.class);
    }

    public static com.google.protobuf.Parser<NotePageSet> PARSER =
        new com.google.protobuf.AbstractParser<NotePageSet>() {
      public NotePageSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NotePageSet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NotePageSet> getParserForType() {
      return PARSER;
    }

    public static final int PAGES_FIELD_NUMBER = 1;
    private java.util.List<com.lys.protobuf.ProtocolNote.NotePage> pages_;
    /**
     * <code>repeated .NotePage pages = 1;</code>
     */
    public java.util.List<com.lys.protobuf.ProtocolNote.NotePage> getPagesList() {
      return pages_;
    }
    /**
     * <code>repeated .NotePage pages = 1;</code>
     */
    public java.util.List<? extends com.lys.protobuf.ProtocolNote.NotePageOrBuilder> 
        getPagesOrBuilderList() {
      return pages_;
    }
    /**
     * <code>repeated .NotePage pages = 1;</code>
     */
    public int getPagesCount() {
      return pages_.size();
    }
    /**
     * <code>repeated .NotePage pages = 1;</code>
     */
    public com.lys.protobuf.ProtocolNote.NotePage getPages(int index) {
      return pages_.get(index);
    }
    /**
     * <code>repeated .NotePage pages = 1;</code>
     */
    public com.lys.protobuf.ProtocolNote.NotePageOrBuilder getPagesOrBuilder(
        int index) {
      return pages_.get(index);
    }

    private void initFields() {
      pages_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < pages_.size(); i++) {
        output.writeMessage(1, pages_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < pages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, pages_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lys.protobuf.ProtocolNote.NotePageSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lys.protobuf.ProtocolNote.NotePageSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NotePageSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lys.protobuf.ProtocolNote.NotePageSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NotePageSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lys.protobuf.ProtocolNote.NotePageSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NotePageSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lys.protobuf.ProtocolNote.NotePageSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NotePageSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lys.protobuf.ProtocolNote.NotePageSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lys.protobuf.ProtocolNote.NotePageSet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NotePageSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NotePageSet)
        com.lys.protobuf.ProtocolNote.NotePageSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lys.protobuf.ProtocolNote.internal_static_NotePageSet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lys.protobuf.ProtocolNote.internal_static_NotePageSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lys.protobuf.ProtocolNote.NotePageSet.class, com.lys.protobuf.ProtocolNote.NotePageSet.Builder.class);
      }

      // Construct using com.lys.protobuf.ProtocolNote.NotePageSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPagesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (pagesBuilder_ == null) {
          pages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          pagesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lys.protobuf.ProtocolNote.internal_static_NotePageSet_descriptor;
      }

      public com.lys.protobuf.ProtocolNote.NotePageSet getDefaultInstanceForType() {
        return com.lys.protobuf.ProtocolNote.NotePageSet.getDefaultInstance();
      }

      public com.lys.protobuf.ProtocolNote.NotePageSet build() {
        com.lys.protobuf.ProtocolNote.NotePageSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lys.protobuf.ProtocolNote.NotePageSet buildPartial() {
        com.lys.protobuf.ProtocolNote.NotePageSet result = new com.lys.protobuf.ProtocolNote.NotePageSet(this);
        int from_bitField0_ = bitField0_;
        if (pagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            pages_ = java.util.Collections.unmodifiableList(pages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.pages_ = pages_;
        } else {
          result.pages_ = pagesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lys.protobuf.ProtocolNote.NotePageSet) {
          return mergeFrom((com.lys.protobuf.ProtocolNote.NotePageSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lys.protobuf.ProtocolNote.NotePageSet other) {
        if (other == com.lys.protobuf.ProtocolNote.NotePageSet.getDefaultInstance()) return this;
        if (pagesBuilder_ == null) {
          if (!other.pages_.isEmpty()) {
            if (pages_.isEmpty()) {
              pages_ = other.pages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePagesIsMutable();
              pages_.addAll(other.pages_);
            }
            onChanged();
          }
        } else {
          if (!other.pages_.isEmpty()) {
            if (pagesBuilder_.isEmpty()) {
              pagesBuilder_.dispose();
              pagesBuilder_ = null;
              pages_ = other.pages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              pagesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPagesFieldBuilder() : null;
            } else {
              pagesBuilder_.addAllMessages(other.pages_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lys.protobuf.ProtocolNote.NotePageSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lys.protobuf.ProtocolNote.NotePageSet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.lys.protobuf.ProtocolNote.NotePage> pages_ =
        java.util.Collections.emptyList();
      private void ensurePagesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          pages_ = new java.util.ArrayList<com.lys.protobuf.ProtocolNote.NotePage>(pages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.lys.protobuf.ProtocolNote.NotePage, com.lys.protobuf.ProtocolNote.NotePage.Builder, com.lys.protobuf.ProtocolNote.NotePageOrBuilder> pagesBuilder_;

      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public java.util.List<com.lys.protobuf.ProtocolNote.NotePage> getPagesList() {
        if (pagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pages_);
        } else {
          return pagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public int getPagesCount() {
        if (pagesBuilder_ == null) {
          return pages_.size();
        } else {
          return pagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public com.lys.protobuf.ProtocolNote.NotePage getPages(int index) {
        if (pagesBuilder_ == null) {
          return pages_.get(index);
        } else {
          return pagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public Builder setPages(
          int index, com.lys.protobuf.ProtocolNote.NotePage value) {
        if (pagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePagesIsMutable();
          pages_.set(index, value);
          onChanged();
        } else {
          pagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public Builder setPages(
          int index, com.lys.protobuf.ProtocolNote.NotePage.Builder builderForValue) {
        if (pagesBuilder_ == null) {
          ensurePagesIsMutable();
          pages_.set(index, builderForValue.build());
          onChanged();
        } else {
          pagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public Builder addPages(com.lys.protobuf.ProtocolNote.NotePage value) {
        if (pagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePagesIsMutable();
          pages_.add(value);
          onChanged();
        } else {
          pagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public Builder addPages(
          int index, com.lys.protobuf.ProtocolNote.NotePage value) {
        if (pagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePagesIsMutable();
          pages_.add(index, value);
          onChanged();
        } else {
          pagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public Builder addPages(
          com.lys.protobuf.ProtocolNote.NotePage.Builder builderForValue) {
        if (pagesBuilder_ == null) {
          ensurePagesIsMutable();
          pages_.add(builderForValue.build());
          onChanged();
        } else {
          pagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public Builder addPages(
          int index, com.lys.protobuf.ProtocolNote.NotePage.Builder builderForValue) {
        if (pagesBuilder_ == null) {
          ensurePagesIsMutable();
          pages_.add(index, builderForValue.build());
          onChanged();
        } else {
          pagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public Builder addAllPages(
          java.lang.Iterable<? extends com.lys.protobuf.ProtocolNote.NotePage> values) {
        if (pagesBuilder_ == null) {
          ensurePagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, pages_);
          onChanged();
        } else {
          pagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public Builder clearPages() {
        if (pagesBuilder_ == null) {
          pages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          pagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public Builder removePages(int index) {
        if (pagesBuilder_ == null) {
          ensurePagesIsMutable();
          pages_.remove(index);
          onChanged();
        } else {
          pagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public com.lys.protobuf.ProtocolNote.NotePage.Builder getPagesBuilder(
          int index) {
        return getPagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public com.lys.protobuf.ProtocolNote.NotePageOrBuilder getPagesOrBuilder(
          int index) {
        if (pagesBuilder_ == null) {
          return pages_.get(index);  } else {
          return pagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public java.util.List<? extends com.lys.protobuf.ProtocolNote.NotePageOrBuilder> 
           getPagesOrBuilderList() {
        if (pagesBuilder_ != null) {
          return pagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pages_);
        }
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public com.lys.protobuf.ProtocolNote.NotePage.Builder addPagesBuilder() {
        return getPagesFieldBuilder().addBuilder(
            com.lys.protobuf.ProtocolNote.NotePage.getDefaultInstance());
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public com.lys.protobuf.ProtocolNote.NotePage.Builder addPagesBuilder(
          int index) {
        return getPagesFieldBuilder().addBuilder(
            index, com.lys.protobuf.ProtocolNote.NotePage.getDefaultInstance());
      }
      /**
       * <code>repeated .NotePage pages = 1;</code>
       */
      public java.util.List<com.lys.protobuf.ProtocolNote.NotePage.Builder> 
           getPagesBuilderList() {
        return getPagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lys.protobuf.ProtocolNote.NotePage, com.lys.protobuf.ProtocolNote.NotePage.Builder, com.lys.protobuf.ProtocolNote.NotePageOrBuilder> 
          getPagesFieldBuilder() {
        if (pagesBuilder_ == null) {
          pagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lys.protobuf.ProtocolNote.NotePage, com.lys.protobuf.ProtocolNote.NotePage.Builder, com.lys.protobuf.ProtocolNote.NotePageOrBuilder>(
                  pages_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          pages_ = null;
        }
        return pagesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:NotePageSet)
    }

    static {
      defaultInstance = new NotePageSet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NotePageSet)
  }

  public interface NoteBookOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NoteBook)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string bookDir = 1;</code>
     */
    boolean hasBookDir();
    /**
     * <code>optional string bookDir = 1;</code>
     */
    java.lang.String getBookDir();
    /**
     * <code>optional string bookDir = 1;</code>
     */
    com.google.protobuf.ByteString
        getBookDirBytes();

    /**
     * <code>optional string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code NoteBook}
   */
  public static final class NoteBook extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NoteBook)
      NoteBookOrBuilder {
    // Use NoteBook.newBuilder() to construct.
    private NoteBook(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NoteBook(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NoteBook defaultInstance;
    public static NoteBook getDefaultInstance() {
      return defaultInstance;
    }

    public NoteBook getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NoteBook(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              bookDir_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lys.protobuf.ProtocolNote.internal_static_NoteBook_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lys.protobuf.ProtocolNote.internal_static_NoteBook_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lys.protobuf.ProtocolNote.NoteBook.class, com.lys.protobuf.ProtocolNote.NoteBook.Builder.class);
    }

    public static com.google.protobuf.Parser<NoteBook> PARSER =
        new com.google.protobuf.AbstractParser<NoteBook>() {
      public NoteBook parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NoteBook(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NoteBook> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BOOKDIR_FIELD_NUMBER = 1;
    private java.lang.Object bookDir_;
    /**
     * <code>optional string bookDir = 1;</code>
     */
    public boolean hasBookDir() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string bookDir = 1;</code>
     */
    public java.lang.String getBookDir() {
      java.lang.Object ref = bookDir_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bookDir_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string bookDir = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBookDirBytes() {
      java.lang.Object ref = bookDir_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bookDir_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>optional string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      bookDir_ = "";
      name_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBookDirBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBookDirBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lys.protobuf.ProtocolNote.NoteBook parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBook parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBook parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBook parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBook parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBook parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBook parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBook parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBook parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBook parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lys.protobuf.ProtocolNote.NoteBook prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NoteBook}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NoteBook)
        com.lys.protobuf.ProtocolNote.NoteBookOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lys.protobuf.ProtocolNote.internal_static_NoteBook_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lys.protobuf.ProtocolNote.internal_static_NoteBook_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lys.protobuf.ProtocolNote.NoteBook.class, com.lys.protobuf.ProtocolNote.NoteBook.Builder.class);
      }

      // Construct using com.lys.protobuf.ProtocolNote.NoteBook.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bookDir_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lys.protobuf.ProtocolNote.internal_static_NoteBook_descriptor;
      }

      public com.lys.protobuf.ProtocolNote.NoteBook getDefaultInstanceForType() {
        return com.lys.protobuf.ProtocolNote.NoteBook.getDefaultInstance();
      }

      public com.lys.protobuf.ProtocolNote.NoteBook build() {
        com.lys.protobuf.ProtocolNote.NoteBook result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lys.protobuf.ProtocolNote.NoteBook buildPartial() {
        com.lys.protobuf.ProtocolNote.NoteBook result = new com.lys.protobuf.ProtocolNote.NoteBook(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bookDir_ = bookDir_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lys.protobuf.ProtocolNote.NoteBook) {
          return mergeFrom((com.lys.protobuf.ProtocolNote.NoteBook)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lys.protobuf.ProtocolNote.NoteBook other) {
        if (other == com.lys.protobuf.ProtocolNote.NoteBook.getDefaultInstance()) return this;
        if (other.hasBookDir()) {
          bitField0_ |= 0x00000001;
          bookDir_ = other.bookDir_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lys.protobuf.ProtocolNote.NoteBook parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lys.protobuf.ProtocolNote.NoteBook) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object bookDir_ = "";
      /**
       * <code>optional string bookDir = 1;</code>
       */
      public boolean hasBookDir() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string bookDir = 1;</code>
       */
      public java.lang.String getBookDir() {
        java.lang.Object ref = bookDir_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bookDir_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bookDir = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBookDirBytes() {
        java.lang.Object ref = bookDir_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bookDir_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bookDir = 1;</code>
       */
      public Builder setBookDir(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bookDir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bookDir = 1;</code>
       */
      public Builder clearBookDir() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bookDir_ = getDefaultInstance().getBookDir();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bookDir = 1;</code>
       */
      public Builder setBookDirBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        bookDir_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NoteBook)
    }

    static {
      defaultInstance = new NoteBook(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NoteBook)
  }

  public interface NoteBookSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NoteBookSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .NoteBook books = 1;</code>
     */
    java.util.List<com.lys.protobuf.ProtocolNote.NoteBook> 
        getBooksList();
    /**
     * <code>repeated .NoteBook books = 1;</code>
     */
    com.lys.protobuf.ProtocolNote.NoteBook getBooks(int index);
    /**
     * <code>repeated .NoteBook books = 1;</code>
     */
    int getBooksCount();
    /**
     * <code>repeated .NoteBook books = 1;</code>
     */
    java.util.List<? extends com.lys.protobuf.ProtocolNote.NoteBookOrBuilder> 
        getBooksOrBuilderList();
    /**
     * <code>repeated .NoteBook books = 1;</code>
     */
    com.lys.protobuf.ProtocolNote.NoteBookOrBuilder getBooksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code NoteBookSet}
   */
  public static final class NoteBookSet extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NoteBookSet)
      NoteBookSetOrBuilder {
    // Use NoteBookSet.newBuilder() to construct.
    private NoteBookSet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NoteBookSet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NoteBookSet defaultInstance;
    public static NoteBookSet getDefaultInstance() {
      return defaultInstance;
    }

    public NoteBookSet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NoteBookSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                books_ = new java.util.ArrayList<com.lys.protobuf.ProtocolNote.NoteBook>();
                mutable_bitField0_ |= 0x00000001;
              }
              books_.add(input.readMessage(com.lys.protobuf.ProtocolNote.NoteBook.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          books_ = java.util.Collections.unmodifiableList(books_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lys.protobuf.ProtocolNote.internal_static_NoteBookSet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lys.protobuf.ProtocolNote.internal_static_NoteBookSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lys.protobuf.ProtocolNote.NoteBookSet.class, com.lys.protobuf.ProtocolNote.NoteBookSet.Builder.class);
    }

    public static com.google.protobuf.Parser<NoteBookSet> PARSER =
        new com.google.protobuf.AbstractParser<NoteBookSet>() {
      public NoteBookSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NoteBookSet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NoteBookSet> getParserForType() {
      return PARSER;
    }

    public static final int BOOKS_FIELD_NUMBER = 1;
    private java.util.List<com.lys.protobuf.ProtocolNote.NoteBook> books_;
    /**
     * <code>repeated .NoteBook books = 1;</code>
     */
    public java.util.List<com.lys.protobuf.ProtocolNote.NoteBook> getBooksList() {
      return books_;
    }
    /**
     * <code>repeated .NoteBook books = 1;</code>
     */
    public java.util.List<? extends com.lys.protobuf.ProtocolNote.NoteBookOrBuilder> 
        getBooksOrBuilderList() {
      return books_;
    }
    /**
     * <code>repeated .NoteBook books = 1;</code>
     */
    public int getBooksCount() {
      return books_.size();
    }
    /**
     * <code>repeated .NoteBook books = 1;</code>
     */
    public com.lys.protobuf.ProtocolNote.NoteBook getBooks(int index) {
      return books_.get(index);
    }
    /**
     * <code>repeated .NoteBook books = 1;</code>
     */
    public com.lys.protobuf.ProtocolNote.NoteBookOrBuilder getBooksOrBuilder(
        int index) {
      return books_.get(index);
    }

    private void initFields() {
      books_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < books_.size(); i++) {
        output.writeMessage(1, books_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < books_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, books_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.lys.protobuf.ProtocolNote.NoteBookSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBookSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBookSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBookSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBookSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBookSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBookSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBookSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBookSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.lys.protobuf.ProtocolNote.NoteBookSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.lys.protobuf.ProtocolNote.NoteBookSet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NoteBookSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NoteBookSet)
        com.lys.protobuf.ProtocolNote.NoteBookSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.lys.protobuf.ProtocolNote.internal_static_NoteBookSet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.lys.protobuf.ProtocolNote.internal_static_NoteBookSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.lys.protobuf.ProtocolNote.NoteBookSet.class, com.lys.protobuf.ProtocolNote.NoteBookSet.Builder.class);
      }

      // Construct using com.lys.protobuf.ProtocolNote.NoteBookSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBooksFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (booksBuilder_ == null) {
          books_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          booksBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.lys.protobuf.ProtocolNote.internal_static_NoteBookSet_descriptor;
      }

      public com.lys.protobuf.ProtocolNote.NoteBookSet getDefaultInstanceForType() {
        return com.lys.protobuf.ProtocolNote.NoteBookSet.getDefaultInstance();
      }

      public com.lys.protobuf.ProtocolNote.NoteBookSet build() {
        com.lys.protobuf.ProtocolNote.NoteBookSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.lys.protobuf.ProtocolNote.NoteBookSet buildPartial() {
        com.lys.protobuf.ProtocolNote.NoteBookSet result = new com.lys.protobuf.ProtocolNote.NoteBookSet(this);
        int from_bitField0_ = bitField0_;
        if (booksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            books_ = java.util.Collections.unmodifiableList(books_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.books_ = books_;
        } else {
          result.books_ = booksBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.lys.protobuf.ProtocolNote.NoteBookSet) {
          return mergeFrom((com.lys.protobuf.ProtocolNote.NoteBookSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.lys.protobuf.ProtocolNote.NoteBookSet other) {
        if (other == com.lys.protobuf.ProtocolNote.NoteBookSet.getDefaultInstance()) return this;
        if (booksBuilder_ == null) {
          if (!other.books_.isEmpty()) {
            if (books_.isEmpty()) {
              books_ = other.books_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBooksIsMutable();
              books_.addAll(other.books_);
            }
            onChanged();
          }
        } else {
          if (!other.books_.isEmpty()) {
            if (booksBuilder_.isEmpty()) {
              booksBuilder_.dispose();
              booksBuilder_ = null;
              books_ = other.books_;
              bitField0_ = (bitField0_ & ~0x00000001);
              booksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getBooksFieldBuilder() : null;
            } else {
              booksBuilder_.addAllMessages(other.books_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.lys.protobuf.ProtocolNote.NoteBookSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.lys.protobuf.ProtocolNote.NoteBookSet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.lys.protobuf.ProtocolNote.NoteBook> books_ =
        java.util.Collections.emptyList();
      private void ensureBooksIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          books_ = new java.util.ArrayList<com.lys.protobuf.ProtocolNote.NoteBook>(books_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.lys.protobuf.ProtocolNote.NoteBook, com.lys.protobuf.ProtocolNote.NoteBook.Builder, com.lys.protobuf.ProtocolNote.NoteBookOrBuilder> booksBuilder_;

      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public java.util.List<com.lys.protobuf.ProtocolNote.NoteBook> getBooksList() {
        if (booksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(books_);
        } else {
          return booksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public int getBooksCount() {
        if (booksBuilder_ == null) {
          return books_.size();
        } else {
          return booksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public com.lys.protobuf.ProtocolNote.NoteBook getBooks(int index) {
        if (booksBuilder_ == null) {
          return books_.get(index);
        } else {
          return booksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public Builder setBooks(
          int index, com.lys.protobuf.ProtocolNote.NoteBook value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.set(index, value);
          onChanged();
        } else {
          booksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public Builder setBooks(
          int index, com.lys.protobuf.ProtocolNote.NoteBook.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.set(index, builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public Builder addBooks(com.lys.protobuf.ProtocolNote.NoteBook value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.add(value);
          onChanged();
        } else {
          booksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public Builder addBooks(
          int index, com.lys.protobuf.ProtocolNote.NoteBook value) {
        if (booksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBooksIsMutable();
          books_.add(index, value);
          onChanged();
        } else {
          booksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public Builder addBooks(
          com.lys.protobuf.ProtocolNote.NoteBook.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.add(builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public Builder addBooks(
          int index, com.lys.protobuf.ProtocolNote.NoteBook.Builder builderForValue) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.add(index, builderForValue.build());
          onChanged();
        } else {
          booksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public Builder addAllBooks(
          java.lang.Iterable<? extends com.lys.protobuf.ProtocolNote.NoteBook> values) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, books_);
          onChanged();
        } else {
          booksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public Builder clearBooks() {
        if (booksBuilder_ == null) {
          books_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          booksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public Builder removeBooks(int index) {
        if (booksBuilder_ == null) {
          ensureBooksIsMutable();
          books_.remove(index);
          onChanged();
        } else {
          booksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public com.lys.protobuf.ProtocolNote.NoteBook.Builder getBooksBuilder(
          int index) {
        return getBooksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public com.lys.protobuf.ProtocolNote.NoteBookOrBuilder getBooksOrBuilder(
          int index) {
        if (booksBuilder_ == null) {
          return books_.get(index);  } else {
          return booksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public java.util.List<? extends com.lys.protobuf.ProtocolNote.NoteBookOrBuilder> 
           getBooksOrBuilderList() {
        if (booksBuilder_ != null) {
          return booksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(books_);
        }
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public com.lys.protobuf.ProtocolNote.NoteBook.Builder addBooksBuilder() {
        return getBooksFieldBuilder().addBuilder(
            com.lys.protobuf.ProtocolNote.NoteBook.getDefaultInstance());
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public com.lys.protobuf.ProtocolNote.NoteBook.Builder addBooksBuilder(
          int index) {
        return getBooksFieldBuilder().addBuilder(
            index, com.lys.protobuf.ProtocolNote.NoteBook.getDefaultInstance());
      }
      /**
       * <code>repeated .NoteBook books = 1;</code>
       */
      public java.util.List<com.lys.protobuf.ProtocolNote.NoteBook.Builder> 
           getBooksBuilderList() {
        return getBooksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.lys.protobuf.ProtocolNote.NoteBook, com.lys.protobuf.ProtocolNote.NoteBook.Builder, com.lys.protobuf.ProtocolNote.NoteBookOrBuilder> 
          getBooksFieldBuilder() {
        if (booksBuilder_ == null) {
          booksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.lys.protobuf.ProtocolNote.NoteBook, com.lys.protobuf.ProtocolNote.NoteBook.Builder, com.lys.protobuf.ProtocolNote.NoteBookOrBuilder>(
                  books_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          books_ = null;
        }
        return booksBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:NoteBookSet)
    }

    static {
      defaultInstance = new NoteBookSet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NoteBookSet)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NotePage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NotePage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NotePageSet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NotePageSet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NoteBook_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NoteBook_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NoteBookSet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NoteBookSet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protocol_note.proto\";\n\010NotePage\022\017\n\007pag" +
      "eDir\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\017\n\007subject\030\003 \001" +
      "(\005\"\'\n\013NotePageSet\022\030\n\005pages\030\001 \003(\0132\t.NoteP" +
      "age\")\n\010NoteBook\022\017\n\007bookDir\030\001 \001(\t\022\014\n\004name" +
      "\030\002 \001(\t\"\'\n\013NoteBookSet\022\030\n\005books\030\001 \003(\0132\t.N" +
      "oteBookB\022\n\020com.lys.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_NotePage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NotePage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NotePage_descriptor,
        new java.lang.String[] { "PageDir", "Title", "Subject", });
    internal_static_NotePageSet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_NotePageSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NotePageSet_descriptor,
        new java.lang.String[] { "Pages", });
    internal_static_NoteBook_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_NoteBook_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NoteBook_descriptor,
        new java.lang.String[] { "BookDir", "Name", });
    internal_static_NoteBookSet_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_NoteBookSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NoteBookSet_descriptor,
        new java.lang.String[] { "Books", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
